### PR TITLE
[add] Social Login Buttons

### PR DESCRIPTION
**Pull request by edbella**
Added social login buttons for Google, Facebook and Twitter using FirebaseUI

### CODE REVIEW

**Comment by edbella** [comment]
I need some help here. The build is failing due to `The current environment does not support the specified persistence type.`. And I do not know how to fix that. It seems to be as a result of firebase. @justiceotuya @olajohn-ajiboye @enyeInc

**Comment by justiceotuya** [comment]
> I need some help here. The build is failing due to `The current environment does not support the specified persistence type.`. And I do not know how to fix that. It seems to be as a result of firebase. @justiceotuya @olajohn-ajiboye @enyeInc

from little research, i can direct you to these links
https://firebase.google.com/docs/auth/web/auth-state-persistence
https://github.com/firebase/firebaseui-web-react/issues/30
https://config9.com/apps/firebase/jest-test-the-current-environment-does-not-support-the-specified-persistence-type/   check this first

**Comment by edbella** [comment]
> > I need some help here. The build is failing due to `The current environment does not support the specified persistence type.`. And I do not know how to fix that. It seems to be as a result of firebase. @justiceotuya @olajohn-ajiboye @enyeInc
> 
> from little research, i can direct you to these links
> https://firebase.google.com/docs/auth/web/auth-state-persistence
> [firebase/firebaseui-web-react#30](https://github.com/firebase/firebaseui-web-react/issues/30)
> https://config9.com/apps/firebase/jest-test-the-current-environment-does-not-support-the-specified-persistence-type/ check this first

@justiceotuya I've stumbled on these links as well and tried the solutions mentioned but it didn't seem to work still.

**Comment by enyeInc** [comment]
You got some merge conflicts and your branch is still broken

**Pull request merged**
